baseurl: https://nanx.me/hugo-renga/
title: Hugo Renga Theme Demo
author: Jane Doe
canonifyurls: yes
languagecode: en
paginate: 3
theme: hugo-renga
enableEmoji: yes
hasCJKLanguage: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _files$
  - _cache$
params:
  copyright: © 2018 Jane Doe
  copyrightUrl: https://nanx.me/hugo-renga/
  email: example@example.com
  faviconfile: image/favicon.png
  github: nanxstats
  highlightjs: yes
  linkedin: nanxstats
  logofile: image/avatar.png
  pagetitle: Jane Doe
  posts_navigation: yes
  progressively: no
  twitter: nanxstats
  uselatex: yes
menu:
  primary:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 2
